openapi: 3.0.0
info:
  title: Harness Feature Flag Version API
  version: 1.0.0
  contact:
    name: Feature Flag - developers
    url: 'https://www.harness.io'
    email: cf@harness.io
servers:
  - url: /api/1.0
    description: no host specified
  - url: 'http://localhost:3000/api/1.0'
    description: CfClient description
paths:
  /version:
    get:
      summary: Request for version
      operationId: GetVersion
      responses:
        '200':
          description: OK
          content:
            application/json; charset=utf-8:
              schema:
                type: object
                properties:
                  versionInfo:
                    type: string
                  gitCommit:
                    type: string
                  adminServiceEnabled:
                    type: boolean
                  clientServiceEnabled:
                    type: boolean
                  metricsServiceEnabled:
                    type: boolean
        '503':
          description: Service Unavailable
  /health:
    get:
      summary: Request basic health status.
      operationId: GetHealthStatus
      responses:
        '200':
          description: OK
          content:
            application/json; charset=utf-8:
              schema:
                type: object
                properties:
                  healthy:
                    type: boolean
        '503':
          description: Service Unavailable
components: {}
